# Generated by Django 3.0.6 on 2021-02-05 15:26

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date_time', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('end_date_time', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('game_status', models.CharField(choices=[('S', 'Start'), ('E', 'End'), ('P', 'Pending'), ('R', 'Result in Progress')], db_index=True, default='P', max_length=1)),
                ('number_of_players', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('no_of_trucks', models.PositiveIntegerField(default=25)),
                ('no_of_turns_per_player', models.PositiveIntegerField(default=5)),
                ('shrink_ratio', models.FloatField(default=0.85)),
                ('growth_ratio', models.FloatField(default=1.1)),
                ('empty_cost_per_truck', models.BigIntegerField(default=400)),
                ('loaded_cost_per_truck', models.BigIntegerField(default=550)),
                ('unused_capital_cost_perTruck', models.BigIntegerField(default=250)),
                ('created_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_ai', models.BooleanField(db_index=True, default=False)),
                ('no_of_ai_player', models.PositiveIntegerField(blank=True, null=True)),
                ('no_of_normal_players', models.PositiveIntegerField(default=2)),
                ('total_trucks_AvailableA2B', models.BigIntegerField(blank=True, default=50, null=True)),
                ('total_trucks_AvailableB2A', models.BigIntegerField(blank=True, default=50, null=True)),
                ('force_t2', models.BooleanField(default=False)),
                ('force_timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 6, 15, 26, 24, 135108))),
                ('brokerage_fee', models.BigIntegerField(default=1200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date_time',),
            },
        ),
        migrations.CreateModel(
            name='WinnerTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_total_net_contribution', models.IntegerField()),
                ('player_rank', models.IntegerField(db_index=True)),
                ('user_nick_name', models.CharField(default='', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricingsimulation.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('terms_condition', models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1)),
                ('activation_key', models.CharField(blank=True, max_length=40, null=True)),
                ('key_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_alive', models.BooleanField(default=False)),
                ('is_ai_player', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGameRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('J', 'Join'), ('B', ' Bid'), ('I', 'Incomplete'), ('T', 'Turn2'), ('Q', 'Quit'), ('E', 'End')], db_index=True, default='E', max_length=1)),
                ('no_of_turns_completed', models.IntegerField(default=0)),
                ('user_nick_name', models.CharField(default='', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_game_record', to='pricingsimulation.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TurnAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_no', models.IntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Fail')], db_index=True, default='F', max_length=1)),
                ('time_Stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricingsimulation.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(choices=[('F', 'Switch to turn1'), ('S', 'Switch to turn2')], default='F', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_notify', to='pricingsimulation.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameSimulationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a2b', models.IntegerField(default=None)),
                ('value_b2a', models.IntegerField(default=None)),
                ('no_of_turn', models.IntegerField(default=1)),
                ('trucks_a2b_Awarded', models.IntegerField(default=12)),
                ('trucks_b2a_Awarded', models.IntegerField(default=15)),
                ('trucks_max_awarded', models.IntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=15)),
                ('loaded_cost', models.BigIntegerField(default=12)),
                ('empty_cost', models.BigIntegerField(default=12)),
                ('net_contribution', models.IntegerField(default=15)),
                ('contribution_per_load', models.IntegerField(default=15)),
                ('loaded_ratio', models.FloatField(default=15)),
                ('bid_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('sum_of_all_bids', models.IntegerField(blank=True, null=True)),
                ('ratio_of_multiplication', models.FloatField(blank=True, null=True)),
                ('simulation_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('fleet_size', models.IntegerField(blank=True, default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='pricingsimulation.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FleetNetContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trucks_max_awarded', models.IntegerField(default=15)),
                ('net_contribution', models.IntegerField(default=0)),
                ('no_of_turn', models.IntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_fleet', to='pricingsimulation.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_fleet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a2b', models.IntegerField()),
                ('value_b2a', models.IntegerField()),
                ('no_of_turn', models.IntegerField(db_index=True, default=1)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sess', to='pricingsimulation.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
